### ISSUE TITLE
Specifying a generatedSourcesDirectory to create a webjar fails the test.

### ISSUE THREAD

**Issue by onigoetz** [st-js/st-js#68] opened 2015-03-30 13:18 UTC
I tried to create a webjar with a library by specifying this in the build configuration:
```html
<generatedSourcesDirectory>${project.build.outputDirectory}/META-INF/resources/webjar/${project.artifactId}</generatedSourcesDirectory>
```

It seems the path in the test is generated completely wrong and all tests fail.
Can you take a look ?

**Comment by npiguet** [comment] 2015-04-01 09:19
Can you make it clearer what the problem is? Which test are you talking about? The ST-JS unit tests? Some tests within your project?

Also I believe that you need to put all the files to be included in your final jar inside the `target/classes` folder (or in your case `target/classes/META-INF`).

**Comment by onigoetz** [comment] 2015-04-08 15:12
Yes sorry, this is not a very precise bug Report.

I have a ST-JS library with unit tests and I want to deliver the library as a webjar thus putting the files in `META-INF/resources/webjar/lib-name/files.js` to use the Servlet 3 static assets delivery system.

This library has ST-JS unit tests and when I run them (`mvn clean install`) it seems it can't find the library's files

**Comment by npiguet** [comment] 2015-04-21 16:03
fixed in master

**Closed by npiguet** 2015-04-21 16:03 UTC

**Comment by onigoetz** [comment] 2015-04-21 16:50
awesome !
